name: rupee_expense_tracker
description: "Daily Expense, Cumulative Savings, and SMS Auto-Tracker App for Indian Rupees."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  telephony_plus: ^1.0.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
